# At least one entry should be present for the plugin to work!
# DO NOT REMOVE EVERYTHING!
BlocksToGenerate:
  cobble:
    block: COBBLESTONE
    block-chance: 4

  stone:
    block: STONE
    block-chance: 2